### ISSUE TITLE
Bootstrapping Framework Components

### ISSUE THREAD

**Issue by vGsteiger** [ubc-cirrus-lab/caribou#284]
Currently we have a deployment script in `scripts/deploy_to_aws.py` which was developed a long time ago. This should theoretically bootstrap and deploy all components as their own serverless functions. This script is very outdated and we should invest some time into deploying the components proper. This would require:

- [ ] Write bootstrapping script
- [ ] Containerise all components
- [ ] Define components interactions (timers, messages), specifically when and how a component triggers another

**Comment by Danidite** [comment]
Moved part of this issue into a separate issue #303 which will be addressed in a separate PR.
